server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        index fr/index.html;  # sert ce fichier directement
    }

    location / {
        try_files $uri $uri/ =404;
    }
}